# Hard Concrete SAE Hyperparameter Sweep Configuration
# Parameters for Hard Concrete SAE training with learnable gates

# Learning rate sweep
learning_rates: [1e-4, 3e-4, 1e-3, 3e-3]

# Sparsity coefficient sweep
sparsity_coeffs: [0.01, 0.03, 0.1, 0.3]

# Dictionary size ratios
dict_size_ratios: [16.0, 32.0, 64.0]

# Training parameters
gradient_accumulation_steps: [20, 40]
warmup_samples: [20_000, 40_000]

# Data parameters
n_train_samples: [50_000, 100_000, 200_000]
train_batch_size: [20, 40]

# Hard Concrete SAE specific parameters
sae_specific:
  # Initial beta values for concrete distribution
  initial_betas: [0.3, 0.5, 1.0, 2.0]
  
  # Whether gates depend on input or are static
  input_dependent_gates: [true, false]

# Experiment limits
max_experiments: 80

# Note: Hard Concrete SAEs learn sparse gates via relaxed Bernoulli variables
# initial_beta controls the sharpness of the concrete distribution
# input_dependent_gates=true allows gates to adapt per input 