# Hard Concrete SAE Hyperparameter Sweep Configuration
# Parameters for Hard Concrete SAE training with learnable gates

saes:
  sparsity_coeffs: [50, 10, 5, 1, 0.5, 0.1, 0.05, 0.01, 0.005]
  input_dependent_gates: [true]